all: recorded_by_hltpath_fromDQM 

recorded_by_hltpath_fromDQM: recorded_by_hltpath_fromDQM.C
	`root-config --cxx --cflags` -I/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/boost/1.63.0/include/ -g -o recorded_by_hltpath_fromDQM recorded_by_hltpath_fromDQM.C  `root-config --libs` -L/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/boost/1.63.0/lib
