all: recorded_by_hltpath_fromDQM 

recorded_by_hltpath_fromDQM: recorded_by_hltpath_fromDQM.C
	`root-config --cxx --cflags` -g -o recorded_by_hltpath_fromDQM recorded_by_hltpath_fromDQM.C  `root-config --libs`
